### PR TITLE
Add 'check' hook

### PR DESCRIPTION
**Pull request by franciscojfs**
Pants can run type check using mypy through the 'check' target. This change brings this capability creating the pants-check hook.

### CODE REVIEW

**Comment by vitalvi** [comment]
@rcuza can this be merged and deployed as the functionality it provides seems to be useful?

**Review by rcuza — APPROVED** [review]
Thank you. This is useful.

**Comment by rcuza** [comment]
@franciscojfs @vitalvi - my apologies for the delay. Didn't even know this little snippet of a repo was forked.

**Comment by vitalvi** [comment]
Thanks a lot @rcuza. 
One more thing, I'd say it would make sense to create a new tag on top of current master in order to be able to stick to it from pre-commit as it doesn't encourage using dynamic branches.

**Pull request merged**
